mysite/lab3/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'lab3'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='lab3:home'), name='logout'),
    path('set_status/', views.set_status, name='set_status'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lab3.urls'))
]

mysite/lab3/models.py
from django.db import models
from django.contrib.auth.models import User


class Status(models.Model):
    status = models.TextField(null=True, max_length=250)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'status_+{self.user}'

mysite/lab3/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Status


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Password dont\'t match')
        return cd['password2']


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['status']

mysite/lab3/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm
from .forms import StatusForm
from .models import Status


def home(request):
    user_status = None

    if request.user.is_authenticated:
        user_status = Status.objects.filter(user=request.user).first()

    return render(request, 'lab3/home.html', {'user_status': user_status})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)  # User obj is created, but not is saved
            cd = user_form.cleaned_data
            new_user.set_password(cd['password'])  # setting chosen password
            new_user.save()  # saving User
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(to='lab3:home')

                else:
                    return HttpResponse("Disabled account")
            else:
                return HttpResponse("Invalid login")
    else:
        user_form = UserRegistrationForm()
    return render(request, 'lab3/register.html', {'user_form': user_form})


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(to='lab3:home')

                else:
                    return HttpResponse("Disabled account")
        else:
            return HttpResponse("Invalid login")
    else:
        form = LoginForm
    return render(request, 'lab3/login.html', {'form': form})


def set_status(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            status = form.save(commit=False)
            status.user = request.user
            status.save()
            return redirect(to='lab3:home')
    else:
        form = StatusForm()
    return render(request, 'lab3/set_status.html', {'form': form})

mysite/lab3/templates/lab3/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'lab3/css/styles.css' %}">
    <link rel="icon" href="{% static 'lab3/favicon/favicon.png' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<header>
    <a href="{% url 'lab3:home' %}">Home</a>
    {% if user.is_authenticated %}
        <a href="{% url 'lab3:logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'lab3:login' %}">Login</a>
        <a href="{% url 'lab3:register' %}">Register</a>
    {% endif %}
</header>
<div class="separator"></div>
{% block content %}
{% endblock %}
</body>
</html>

mysite/lab3/templates/lab3/home.html
{% extends "lab3/base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="home">
    {% if user.is_authenticated %}
        <h4>Hi, user {{ user.username }}</h4>
        {% if user_status %}
            <h5>{{ user_status.status }}</h5>
        {% else %}
            <a href="{% url 'lab3:set_status' %}">Set Status</a>
        {% endif %}
    {% else %}
        This is home page.
    {% endif %}

</div>

{% endblock %}

mysite/lab3/templates/lab3/login.html
{% extends 'lab3/base.html' %}

{% block title %}Вход{% endblock %}

{% block content %}
    <div class="home">
        <h2>Вход</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Войти</button>
        </form>
    </div>
{% endblock %}

mysite/lab3/templates/lab3/register.html
{% extends 'lab3/base.html' %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <div class="home">
        <h2>Регистрация</h2>
        <form method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            <button type="submit">Зарегистрироваться</button>
        </form>
    </div>
{% endblock %}

mysite/lab3/templates/lab3/set_status.html
{% extends 'lab3/base.html' %}

{% block title %}Статус{% endblock %}

{% block content %}
    <div class="home">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Set Status</button>
        </form>
    </div>
{% endblock %}